package me.gabryon.kodeedelivery.utility

import ch.hippmann.godot.utilities.logging.debug
import godot.FileAccess
import godot.global.GD.abs
import godot.global.GD.fmod
import godot.util.PI
import godot.util.TAU
import kotlin.experimental.ExperimentalTypeInference
import kotlin.reflect.KProperty

/**
 * Adds two integers safely, ensuring no arithmetic overflow occurs.
 *
 * @param value The value to be added to this integer.
 * @return The sum of this integer and the given value. If an arithmetic overflow occurs, it returns Int.MAX_VALUE.
 */
infix fun Int.safeAdd(value: Int): Int = try {
    Math.addExact(this, value)
} catch (e: ArithmeticException) {
    Int.MAX_VALUE
}

/**
 * Calculates the value obtained by increasing the given number by a certain percentage.
 *
 * @param percentage The percentage by which the number should be increased. Typically, the number is between 1 and 100.
 * @return The value is obtained after increasing the number by the given percentage.
 */
infix fun Double.increasedByFactorOf(percentage: Double): Double = this * (1.0 + percentage / 100.0)

/**
 * Returns an infinite sequence generated by the given [block] function.
 *
 * @param block the block function to generate the sequence elements.
 * @return an infinite sequence.
 *
 * @param T the type of elements in the sequence.
 */
@OptIn(ExperimentalTypeInference::class)
fun <T> infiniteSequence(@BuilderInference block: suspend SequenceScope<T>.() -> Unit): Sequence<T> = Sequence {
    iterator {
        while (true) block()
    }
}

/**
 * Executes the given block of code indefinitely in a loop.
 *
 * @param block The code block to be executed in each iteration of the loop.
 */
inline fun loop(block: () -> Unit) {
    while (true) block()
}

/**
 * Calculates the absolute angular distance between two angles in radians.
 *
 * @param from The starting angle.
 * @param to The ending angle.
 * @return The absolute angular distance between the two angles.
 */
fun absoluteAngularDistance(from: Double, to: Double): Double {
    val angle1 = fmod(from, TAU)
    val angle2 = fmod(to, TAU)
    val diff = abs(angle1 - angle2)
    return when {
        diff > PI -> TAU - diff
        else -> diff
    }
}

/**
 * Calculates the absolute angular distance between two angles in radians.
 *
 * @param from The starting angle.
 * @param to The ending angle.
 * @return The absolute angular distance between the two angles.
 */
fun absoluteAngularDegreesDistance(from: Double, to: Double): Double {
    val diff = abs(from - to)
    return when {
        diff > 360.0 -> 360.0 - diff
        else -> diff
    }
}

/**
 * Calculates the angular distance between two angles in radians.
 *
 * @param from The starting angle.
 * @param to The ending angle.
 * @return The angular distance between the two angles.
 */
fun angularDistance(from: Double, to: Double): Double {
    val angle1 = fmod(from, TAU)
    val angle2 = fmod(to, TAU)
    val diff = angle2 - angle1
    return when {
        diff > PI -> diff - TAU
        diff < -PI -> diff + TAU
        else -> diff
    }
}

/**
 * Provides access to a file specified by the given path using the specified modes.
 * The file resource is automatically closed.
 *
 * @param path The path of the file to access.
 * @param modes The modes to open the file with.
 * @param body The lambda expression to execute within the file context.
 * @return The result of executing the lambda expression on the file context, or null if an error occurred.
 */
inline fun <T> fileAccess(path: String, modes: FileAccess.ModeFlags, body: FileAccess.() -> T): T? {
    val file = FileAccess.open(path, modes)
    return try {
        file?.body()
    } finally {
        file?.close()
    }
}

inline fun <T> debugLine(silence: Boolean = false, writer: DebugLineSession.() -> T): T {
    val session = DebugLineSession()
    return try {
        session.writer()
    } finally {
        if (!silence) session.debugLines()
    }
}

class DebugLineSession {
    
    private val vars = mutableMapOf<String, Any?>()
    operator fun <T> T.getValue(nothing: Nothing?, property: KProperty<*>): T = this.dbg(property.name)
    private fun <T> T.dbg(name: String): T = this.also { vars[name] = this }

    @PublishedApi
    internal fun debugLines() {
        vars
            .entries
            .joinToString { (name, value) -> "$name = $value" }
            .also(::debug)
    }

    /**
     * Utility function to trigger the delegation getter.
     */
    fun hole(vararg a: Any?): Nothing? = null
}
